{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smokify.serviceAccountName" . }}
  labels:
{{ include "smokify.labels" . | nindent 4 }}
{{- end -}}
